DELETE FROM RESERVE;
DELETE FROM TOURCON;
DELETE FROM TOURINFO;
DELETE FROM CUSTOMER;
DELETE FROM EMPLOYEE;
DELETE FROM AGE;
DELETE FROM ACCOMMODATION;
DELETE FROM ARRIVAL;
DELETE FROM DEPARTURE;

COMMIT;
