DROP TABLE IF EXISTS RESERVE;
DROP TABLE IF EXISTS TOURCON;
DROP TABLE IF EXISTS TOURINFO;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS AGE;
DROP TABLE IF EXISTS ACCOMMODATION;
DROP TABLE IF EXISTS ARRIVAL;
DROP TABLE IF EXISTS DEPARTURE;

COMMIT;

