INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000001', 'データ太郎', 'データタロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000002', 'データ次郎', 'データジロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000003', 'データ三郎', 'データサブロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000004', 'データ四郎', 'データシロウ', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_KANA, STAFF_PASS) VALUES ('00000005', 'データ五郎', 'データゴロウ', 'password');

COMMIT;