DROP TABLE RESERVE;
DROP TABLE TOURCON;
DROP TABLE TOURINFO;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE AGE;
DROP TABLE ACCOMMODATION;
DROP TABLE ARRIVAL;
DROP TABLE DEPARTURE;

COMMIT;

